[package]
name = "asasas"
version = "0.14.0"
readme = "README.md"

[package.metadata.docs.rs]
features = ["icon_loading"]

[features]
icon_loading = ["image"]

[dependencies]
lazy_static = "1.0.0"
libc = "0.2.37"
image = {version = "0.19.0",optional = true}

[dev-dependencies]
tempdir = "0.3.7"

[build-dependencies]
gcc = "0.3.54"

[target.'cfg(target_os = "android")'.dependencies.android_glue]
version = "0.2"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2.1"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
cocoa = "0.15.0"
core-foundation = "0.6.0"
core-graphics = "0.14.0"

[target.'cfg(unix)'.dev-dependencies]
mio = "0.6.14"


[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3"
features = [
    "winnt",
    "winuser",
    "wingdi",
    "shellapi",
    "dwmapi",
    "processthreadsapi",
    "libloaderapi",
    "windowsx",
    "hidusage",
    "combaseapi",
    "objbase",
    "unknwnbase",
]

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "openbsd"))'.dependencies]
wayland-client = {version = "0.10.3",features = ["dlopen","egl","cursor"]}
smithay-client-toolkit = "0.2.1"
x11-dl = "2.17.5"
parking_lot = "0.5.5"
percent-encoding = "1.0.1"